extends:
  - "plugin:mdx/recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "plugin:react/recommended"
  - "eslint:recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
env:
  browser: true
  es6: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  ecmaFeatures":
    jsx: true
plugins:
  - react
  - prettier
  - "@typescript-eslint"
  - "react-hooks"
rules:
  "react-hooks/rules-of-hooks": "error"
  "react-hooks/exhaustive-deps": "warn"
  "react/no-unescaped-entities": "warn"
overrides:
  - env:
      jest: true
    files:
      - "src/**/*.{test,spec}.{js,jsx,ts,tsx}"
  - files:
      - "*.md"
    rules:
      prettier/prettier:
        - 2
        - parser: markdown
  - files:
      - "*.{md,mdx}"
    extends:
      - plugin:mdx/overrides
