extends:
  - "eslint:recommended"
  - "plugin:import/recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
  - "prettier/@typescript-eslint"
env:
  browser: true
  es6: true
  jest: true
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: 2018
  ecmaFeatures":
    jsx: true
plugins:
  - react
  - prettier
  - "@typescript-eslint"
  - "react-hooks"
rules:
  "react-hooks/rules-of-hooks": "error"
  "react-hooks/exhaustive-deps": "warn"
  "react/no-unescaped-entities": "warn"
